spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liugogal/configs.git
          username: liugogal
          password: gogalggoo
          basedir: ./basePath
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

